[package]
name = "rc_async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
futures-core = "0.3.30"

[dev-dependencies]
futures = "0.3.30"

